version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: easybook-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: easybook
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - easybook-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: easybook-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/easybook?authSource=admin
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
      - JWT_EXPIRES_IN=7d
      - EMAIL_USER=your_email@gmail.com
      - EMAIL_PASS=your_gmail_app_password
      - EMAIL_FROM=your_email@gmail.com
      - VN_PAY_SECRET=demo_vnp_secret_key
      - VN_PAY_TMN_CODE=demo_tmn_code
      - MOMO_SECRET=test_momo_secret_key
      - MOMO_ACCESS_KEY=test_momo_access_key
      - PAYPAL_CLIENT_ID=test_paypal_client_id
      - PAYPAL_CLIENT_SECRET=test_paypal_client_secret
      - BASE_URL=http://localhost:3000
      - API_URL=http://localhost:3001
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - easybook-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: easybook-frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NEXT_PUBLIC_APP_NAME=EasyBook
      - NEXT_PUBLIC_VNPAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - NEXT_PUBLIC_MOMO_URL=https://test-payment.momo.vn/v2/gateway/api/create
      - NEXT_PUBLIC_PAYPAL_URL=https://www.sandbox.paypal.com
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - easybook-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: easybook-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - easybook-network

volumes:
  mongodb_data:
    driver: local

networks:
  easybook-network:
    driver: bridge 